version: '3.4'

services:
  portainer:
    image: portainer/portainer-ce
  
  mongo.express:
    image: mongo-express

  catalogdb:
    image: mongo

  catalog.api.services:
    image: ${DOCKER_REGISTRY-}catalogapiservices
    build:
      context: .
      dockerfile: Services/Catalog.API/Catalog.API.Services/Dockerfile

  ocelotapigateway:
    image: ${DOCKER_REGISTRY-}ocelotapigateway
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGateway/Dockerfile
 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2

  webstatus:
    image: ${DOCKER_REGISTRY-}webstatus
    build:
      context: .
      dockerfile: WebApps/WebStatus/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  elasticsearch-data:
